# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9a01c3e875cdaaeefa562ae58c946df16b26717871139ac31f867fc16b6fc99023cf8393388ee1bd29ad9089add2b6d1d9bb8ee26074b8c738e8c669fb610ee

test:
  secret_key_base: 97ed3c0d7fb57c998ec71cb9f93a3f95b6eceed891aec82999754d9a6a04c9034d93630753930d37cc99cba139ff27f6386e2be49be277cdd3e89509aa1457be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
